bdd/urls.py
# Importamos la función path para definir patrones de URL
from django.urls import path
# Importamos la vista WelcomeView que acabamos de crear
from .views_old import Imprimir, usuarios_caja, consultar_carrito, crear_modificar_lista_pedidos, ItemsView 
from .views_old import seleccionar_proveedor, cambiar_cantidad_pedido, editar_item, agregar_articulo_a_carrito
from .views_old import carrito, eliminar_articulo_pedido, ListarCarteles, descargar_archivo
from .views_old import reportar_item, enviar_reporte

app_name = 'bdd'


from .models import NavBar, Armador
from django.utils.module_loading import import_string

from pedido.views.externo import agregar_al_pedido


try:
    # Generamos una lista de objetos path a partir de la información almacenada en el modelo Armador
    armador_paths = []
    #print('1')
    dos = NavBar.objects.all()
    #print('2')
    i = 0
    for nav_bar in NavBar.objects.all():
        try:
            i = i + 1
            #print(i, "-", nav_bar)
            armador = Armador.objects.get(nav_bar=nav_bar)
            vista = import_string(f'bdd.views.{armador.vista}')
            armador_paths.append(path(nav_bar.url_inicial, vista.as_view(), name=nav_bar.text_display))
            #print(armador)
            #print(vista)
            #print(armador_paths)
        except:
            pass
    #print('3')
    print('armador_paths: \n')
    for p in armador_paths:
        print(p)
except Exception as e:
    armador_paths = []
    print("'Error en urls.py; se establecera 'armador_paths = []'")
    print('Error:')
    print(e)
# Definimos nuestros patrones de URL
urlpatterns = [
    # Incluimos los patrones de URL generados dinámicamente
    *armador_paths,
]

# Agregamos los patrones de URL para la vista Imprimir después de agregar los patrones dinámicos
urlpatterns += [
    path('items/<int:cajon_id>', ItemsView.as_view(), name='items'),
    path('seleccionar_proveedor/', seleccionar_proveedor, name='seleccionar_proveedor'),
    path('carrito/', carrito, name='carrito'),
    path('editar_item/<int:id_articulo>/', editar_item, name='editar_item'),
    path('agregar_articulo_a_carrito/<int:id_articulo>/', agregar_articulo_a_carrito, name='agregar_articulo_a_carrito'),
    path('cambiar_cantidad_pedido/<int:id_articulo>/<int:cantidad>/', cambiar_cantidad_pedido, name='cambiar_cantidad_pedido'),
    path('crear_modificar_lista_pedidos/', crear_modificar_lista_pedidos, name='mi_vista_ajax'),
    path('consultar_carrito/', consultar_carrito, name='consultar_carrito'),
    path('usuarios_caja/', usuarios_caja, name='usuarios_caja'),
    path('eliminar_articulo_pedido/', eliminar_articulo_pedido, name='eliminar_articulo_pedido'),
    path('crear_modificar_lista_pedidos/<int:proveedor_id>', crear_modificar_lista_pedidos, name='mi_vista_ajax_get'),
    path('imprimir/',Imprimir.as_view(), name='imprimir'),
    path('imprimir/tabla/',Imprimir.as_view(), name='imprimir tabla'),
    path('imprimir/carteles/1/',Imprimir.as_view(), name='imprimir 1 cartel'),
    path('listar_carteles/',ListarCarteles.as_view(), name='listar_carteles'),
    path('descargar_archivo/', descargar_archivo, name='descargar_archivo'),
    path('agregar_articulo_a_pedido/<int:articulo_id>/', agregar_al_pedido, name='agregar_articulo_a_pedido'),
    path('reportar_item/<int:articulo_id>/', reportar_item , name='reportar_item'),
    path('enviar_reporte/<int:articulo_id>/', enviar_reporte , name='enviar_reporte'),
]
# for url in urlpatterns:
#     print(url)
# Incluimos otros patrones de URL estáticos
# urlpatterns += [
#     path('inicio/', MiVista.as_view(), name='inicio'),
#     path('', MiVista.as_view(), name='inicio'),
# ]

core_config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
#from pruebas_conexion_api import urls as urls_pruebas_conexion_api
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', include('carga_archivo.urls')),
    path('', include('facturacion.urls')),
    path('', include('boletas.urls')),
    path('pedidos/', include('pedido.urls')),
    path('', include('x_cartel.urls')),
    path('', include('x_articulos.urls')),
    path('', include('bdd.urls')),
    path('', include('core_docs.urls')),
    path('', include('core_index.urls')),
    path('', include('actualizador.urls')),
    path('uml/', include('uml_visualizer.urls', namespace='uml_visualizer')),
    #path('testing/', include('core_testing.urls', namespace='core_testing')),
    path('', RedirectView.as_view(url='/bienvenida/'), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    #path('',include(urls_pruebas_conexion_api)),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

]


urlpatterns += [
    re_path(r"^media/(?P<path>.*)$", serve, {
        'document_root':settings.MEDIA_ROOT,
        }),
    
    re_path(r"^static/(?P<path>.*)$", serve, {
        'document_root':settings.STATIC_ROOT,
        })

]

pedido/urls.py
from django.urls import path
from .views.base import ItemAutocomplete, agregar_al_stock
from .views.controlar import ControlarPedidoView, agregar_devolucion, actualizar_llego
from .views.detalles import DetallePedidoView
from .views.devoluciones import ListarDevolucionesView, actualizar_cantidad
from .views.editar import EditarPedidoView, actualizar_cantidad, agregar_al_pedido
from .views.editar import cancelar_articulo_pedido, enviar_pedido
from .views.faltantes import ListarArticulosFaltantesView
from .views.home import HomeView, nuevo_pedido

app_name = 'pedido'
name = 'pedido'

urlpatterns = [
     #Home vista de inicio
     path('home/',
         HomeView.as_view(),
         name='home'
         ), 
     
     path('nuevo_pedido/<int:proveedor_id>',
         nuevo_pedido,
         name='nuevo-pedido'
         ),
     
     #Buscar articulos
     path('item_autocomplete/',
         ItemAutocomplete.as_view(),
         name='item-autocomplete'
         ),
     
     path('agregar_al_stock/',
         agregar_al_stock,
         name='agregar-al-stock'
         ),
     
     #Listar articulos faltantes
     path('listar_faltantes/<int:proveedor_id>',
         ListarArticulosFaltantesView.as_view(),
         name='listar-faltantes'
         ), 
     
     #Editar pedido por proveedor
     path('editar_pedido_por_proveedor/<int:proveedor_id>',
         EditarPedidoView.as_view(),
         name='editar-pedido-por-proveedor'
         ),
     
     path('editar_pedido/<int:pedido_id>',
         EditarPedidoView.as_view(),
         name='editar-pedido'
         ),
     
     path('actualizar_cantidad/<int:articulo_id>',
         actualizar_cantidad,
         name='actualizar-cantidad'
         ),
     
     path('agregar_al_pedido/',
         agregar_al_pedido,
         name='agregar-al-pedido'
         ),
     
     path('cancelar_articulo_pedido/',
         cancelar_articulo_pedido,
         name='cancelar-articulo-pedido'
         ),
     
     path('enviar_pedido/',
         enviar_pedido,
         name='enviar-pedido'
         ),
     
     #Detalle de pedido por proveedor
     path('detalle_pedido/<int:pedido_id>',
         DetallePedidoView.as_view(),
         name='detalle-pedido'
         ),
     
     #Controlar pedido por proveedor
     path('controlar_pedido/<int:pedido_id>',
         ControlarPedidoView.as_view(),
         name='controlar-pedido'
         ),
     
     path('agregar_devolucion/',
         agregar_devolucion,
         name='agregar-devolucion'
         ),
     
     path('actualizar_llego/<int:articulo_id>',
         actualizar_llego,
         name='actualizar-llego'
         ),
     
     path('marcar_controlado/',
         ControlarPedidoView.as_view(),
         name='marcar-controlado'
         ),
     
     #Listar devoluciones
     path('listar_devoluciones/',
         ListarDevolucionesView.as_view(),
         name='listar-devoluciones'
         ),
     
     path('actualizar_cantidad/<int:articulo_id>',
         actualizar_cantidad,
         name='actualizar-cantidad'
         ),
     
     path('eliminar_devolucion/',
         ListarDevolucionesView.as_view(),
         name='eliminar-devolucion'
         ),
     

]

pedido/models.py
from datetime import timezone
from django.db import models

from bdd.models import Item, Proveedor, Lista_Pedidos

  
class Vendido(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    cantidad = models.FloatField(default=0.0)
    
    umbral = models.FloatField(default=0.0)
    
    pedido = models.BooleanField(default=False)

class ArticuloPedido(models.Model):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    cantidad = models.FloatField(default=0.0)
    
    llego = models.BooleanField(default=False)
    
    fecha = models.DateField(auto_created=True, default='2021-01-01')
    
class Pedido(models.Model):
    ESTADOS_PEDIDOS = (
        ('Pd', 'Pendiente'),
        ('En', 'Enviado'),
        ('Et', 'Entregado'),
        ('Co', 'Controlado'),
    )
    
    fecha = models.DateField(auto_now_add=True, blank=True, null=True)
    
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    
    articulo_pedido = models.ManyToManyField(ArticuloPedido)
    
    total = models.FloatField(default=0.0)
    
    fecha_entrega = models.DateField(blank=True, null=True)
    
    estado = models.CharField(max_length=20, choices=ESTADOS_PEDIDOS, default='Pd')
    
    def __str__(self):
        return str(self.fecha) + " " + str(self.proveedor) + " " + str(self.estado)

class ArticuloDevolucion(models.Model):
    fecha = models.DateField(auto_now_add=True, blank=True, null=True)
    
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    
    cantidad = models.FloatField(default=0.0)
    
    def __str__(self):
        return str(self.fecha) + " " + str(self.proveedor) + " " + str(self.item) + " " + str(self.cantidad)

pedido/views/base.py
from django.views.generic import TemplateView
from dal_select2.views import Select2QuerySetView
from bdd.models import Item, Proveedor, Lista_Pedidos
from django.http import JsonResponse
import json
from pedido.models import ArticuloPedido

class GeneralPedidoView(TemplateView):
    ''' Vista a modo de interfaz para las operaciones generales de pedidos
    '''
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['barra_de_navegacion']= [
            {'text_display': 'Listar Pedidos', 'url': {'ruta': 'pedidos/home/'}},
            {
                'text_display': 'Sección 2',
                'subsecciones': [
                    {'text_display': 'Subsección 2.1', 'url': {'ruta': 'subseccion21'}},
                    {'text_display': 'Subsección 2.2', 'url': {'ruta': 'subseccion22'}},
                ]
            },
            {'text_display': 'Listar Devoluciones', 'url': {'ruta': 'pedidos/listar_devoluciones/'}},
        ]
        return context
    

class ItemAutocomplete(Select2QuerySetView):
    def get_queryset(self):
        print("get_queryset called")
        if not self.request.user.is_authenticated:
            print("User is not authenticated")
            return Item.objects.none()

        qs = Item.objects.all()
        
        codigo = self.request.GET.get('q', None)
        proveedor_id = self.request.GET.get('proveedor_id')
        proveedor = Proveedor.objects.get(id=proveedor_id)
        print(f"codigo: {codigo}, proveedor_id: {proveedor_id}")
        
        if codigo:
            print(f"Filtering items with codigo starting with {codigo}")
            qs = qs.filter(codigo__istartswith=codigo, codigo__endswith=proveedor.identificador.abreviatura)
            print('abreviatura:', proveedor.identificador.abreviatura)
        print(f"Returning {len(qs)} items")
        print(qs)
        return qs
    
    def render_to_response(self, context):
        # Transforma la lista de items a una lista de diccionarios con 'id' y 'text'
        data = {
            'items': [{'id': item.id, 'text': str(item)} for item in context['object_list']],
            'total_count': len(context['object_list'])
        }
        return JsonResponse(data)
    
def agregar_al_stock(request):
    # Código para agregar un artículo al stock
    data = json.loads(request.body)
    print("Agregando al stock", data)
    articulo_pedido = ArticuloPedido.objects.get(id=data.get('articulo_id'))
    articulo_pedido.llego = data.get('llego')
    articulo_pedido.item.stock = articulo_pedido.item.stock + articulo_pedido.cantidad
    articulo_pedido.cantidad = 0
    
    articulo_faltante, _ = Lista_Pedidos.objects.get_or_create(proveedor_id=articulo_pedido.proveedor.id, item_id=articulo_pedido.item.id)
    articulo_faltante.pedido = False
    articulo_faltante.cantidad = articulo_faltante.cantidad - float(1)
    articulo_faltante.save()
    
    articulo_pedido.item.save()
    articulo_pedido.save()
    return JsonResponse({'status': 'ok'})

pedido/views/controlar.py
from .base import GeneralPedidoView
import json
from django.http import JsonResponse
from pedido.models import ArticuloPedido, Pedido, ArticuloDevolucion
from bdd.models import Lista_Pedidos
from pedido.forms import ArticuloPedidoForm

class ControlarPedidoView(GeneralPedidoView):
    template_name = 'pedido/vistas/controlar_pedido/base.html'
    
    def get_context_data(self, pedido_id, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pedido'] = Pedido.objects.get(id=pedido_id)
        context['proveedor'] = context['pedido'].proveedor
        context['Lista_articulos_pedidos'] = ArticuloPedido.objects.filter(pedido=pedido_id)
        context['form'] = ArticuloPedidoForm()
        return context
    
    def get(self, request, pedido_id):
        # Código para controlar un pedido
        context = self.get_context_data(pedido_id=pedido_id)

        return self.render_to_response(context)
    
    def post(self, request):
        data = json.loads(request.body)
        pedido_id = data.get('pedido_id')
        context = self.get_context_data(pedido_id=pedido_id)
        print("Controlando pedido", data)
        pedido_controlado = Pedido.objects.get(id=pedido_id)
        pedido_controlado.estado = 'Co'
        context['lista_articulo_que_no_llegaron'] = ArticuloPedido.objects.filter(pedido=pedido_id, llego=False)
        pedido, _ = Pedido.objects.get_or_create(proveedor=pedido_controlado.proveedor, estado='Pd')
        pedido.articulo_pedido.add(*context['lista_articulo_que_no_llegaron'])
        
        pedido.save()
        pedido_controlado.save()
        return JsonResponse({'status': 'ok'})
    
def agregar_devolucion(request):
    # Código para agregar un artículo a una devolución
    data = json.loads(request.body)
    print("Agregando devolución", data)
    #se desvincula el articulo del pedido y se vincula a la lista de devolucion
    articulo_pedido = ArticuloPedido.objects.get(id=data.get('articulo_id'))

    pedido = Pedido.objects.get(id=data.get('pedido_id'))
    pedido.articulo_pedido.remove(articulo_pedido)
    
    articulo = Lista_Pedidos.objects.get(proveedor=articulo_pedido.proveedor, item=articulo_pedido.item)
    articulo.pedido = False
    
    devolucion = ArticuloDevolucion.objects.create(
        proveedor=articulo_pedido.proveedor,
        item=articulo_pedido.item,
        cantidad=articulo_pedido.cantidad
    )
    
    articulo_pedido.cantidad = 0   
     
    pedido.save()
    devolucion.save()
    articulo_pedido.save()
    articulo.save()
    return JsonResponse({'status': 'ok'})

def actualizar_llego(request, articulo_id):
    # Código para actualizar el campo llego de un pedido
    print("Actualizando llego de articulo", articulo_id)
    articulo_pedido = ArticuloPedido.objects.get(id=articulo_id)
    data = json.loads(request.body)
    articulo_pedido.llego = data.get('llego')
    # Process the data as needed
    
    
    articulo_faltante, _ = Lista_Pedidos.objects.get_or_create(proveedor_id=articulo_pedido.proveedor.id, item_id=articulo_pedido.item.id)
    articulo_faltante.pedido = False
    articulo_faltante.cantidad = articulo_faltante.cantidad - float(1)
    articulo_faltante.save()
    
    articulo_pedido.save()
    return JsonResponse({'status': 'ok'})

pedido/views/detalles.py
from .base import GeneralPedidoView
from pedido.models import Pedido

class DetallePedidoView(GeneralPedidoView):
    template_name = 'pedido/vistas/detalle_pedido/base.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Código para listar los pedidos
        pedido_id = self.kwargs.get('pedido_id')
        context['pedido'] = Pedido.objects.get(id=pedido_id)
        context['articulos'] = context['pedido'].articulo_pedido.all()
        return context

    def get(self, request, pedido_id):
        context = self.get_context_data()
        return self.render_to_response(context)

pedido/templates/pedido/base_pedido.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block encabezado %}
    {% endblock %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <title>{% block title %}  {% endblock%}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}">
    <link rel="shortcut icon" type="image/png" href="/media/imagenes/favicon.ico"/>
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="/media/imagenes/favicon.ico"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    
    <style>
        #id_item {
            width: 100%
        }
    </style>
    {% include 'pedido/nav_bar.html' %}

</head>
<body>
    <script src="{% static 'cookies/js-cookies3.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'quagga/quagga.js' %}"></script>
    
    {% block cuerpo %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    {% block script %}
    {% endblock %}
    

</body>

</html>

pedido/templates/pedido/detalles_pedido.html
{% extends "pedido/base_pedido.html" %}

{% block encabezado %}
    <title>Detalles del Pedido</title>
    {% load static %}
{% endblock %}

{% block cuerpo %}
{% csrf_token %}
<h2>Pedido: {{ proveedor }}</h2>
<button onclick="controlarPedido({{ pedido.id }})">ControlarPedido</button>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>fecha</th>
            <th>Proveedor</th>
            <th>Ítem</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in Lista_articulos_pedidos %}
            <tr>
                <td>{{ articulo.id }}</td>
                <td>{{ articulo.fecha }}</td>
                <td>{{ articulo.proveedor }}</td>
                <td>{{ articulo.item }}</td>
                <td>{{ articulo.cantidad}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
    
{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        function controlarPedido(id){
            $.ajax({
                url: '/pedido/controlar_pedido/'+id,
                type: 'POST',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response){
                    alert(response);
                }
            });
        }
    </script>

{% endblock %}

pedido/templates/pedido/listar_faltantes.html
{% extends "pedido/base_pedido.html" %}

{% block encabezado %}
    <title>Agregar Articulo Pedido</title>
    {% load static %}
{% endblock %}

{% block cuerpo %}
{% csrf_token %}
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Proveedor</th>
            <th>Ítem</th>
            <th>Cantidad</th>
            <th>Pedir?</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in lista_articulos_faltantes %}
            <tr>
                <td>{{ articulo.id }}</td>
                <td>{{ articulo.proveedor }}</td>
                <td>{{ articulo.item }}</td>
                <td>{{ articulo.cantidad }}</td>
                <td>{{ articulo.pedido }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block script %}

{% endblock %}

pedido/templates/pedido/nav_bar.html
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
        <a class="navbar-brand" href="/buscador/">Ferreteria Paoli</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for nav in barra_de_navegacion %}
                    {% if nav.subsecciones %}  <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle btn" href="#" id="navbarDropdown{{ forloop.counter }}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ nav.text_display }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown{{ forloop.counter }}">
                                {% for subseccion in nav.subsecciones %}
                                    <li><a class="dropdown-item" href="/{{ subseccion.url.ruta }}">{{ subseccion.text_display }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% elif nav.text_display == 'Actualizar' %}
                        <a href="/actualizar/" class="btn btn-primary position-relative">
                            <i class="fa fa-file"></i> Planillas
                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                {{ nuevas_planillas }}
                                <span class="visually-hidden">nuevas planillas</span>
                            </span>
                        </a>
                    {% else %}
                        <a class="nav-link btn" href="/{{ nav.url.ruta }}">{{ nav.text_display }}</a>
                    {% endif %}
                {% endfor %}
                {% if user.is_authenticated %}
                    <a class="nav-link btn" href="{% url 'logout'%}?next={{request.path}}">{{ user.get_username }}: Cerrar Usuario</a>
                {% else %}
                    <a class="nav-link btn" href="{% url 'login'%}?next={{request.path}}">Ingresar</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>